#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

GROUP_ID[100]='cis-1.3'
GROUP_NUMBER[100]='100.0'
GROUP_TITLE[100]='CIS 1.3 - [cis-1.3] ************************************'
GROUP_RUN_BY_DEFAULT[100]='N' # run it when execute_all is called
GROUP_CHECKS[100]='check117,check118,check115,check112,chek113,check114,check11,check19,check110,check12,check121,check111,custom7114,check14,check116,check122,check120,check119,custom7115,extra734,extra769,extra734,extra764,extra729,check21,check22,check23,check24,check25,check26,check27,check28,check29,extra725,check31,check32,check33,check34,check35,check36,check37,check38,check39,check310,check311,check312,check313,check314,custom315'
