#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
CHECK_ID_extra7114="7.114"
CHECK_TITLE_extra7114="[extra7114] Ensure there is only one active access key available for any single IAM user"
CHECK_SCORED_extra7114="NOT_SCORED"
CHECK_TYPE_extra7114="EXTRA"
CHECK_SEVERITY_extra7114="Medium"
CHECK_ASFF_RESOURCE_TYPE_extra7114="AwsIamUser"
CHECK_ALTERNATE_check7114="extra7114"

extra7114(){
  # "Ensure there is only one active access key available for any single IAM user"
  LIST_USERS=$($AWSCLI iam list-users --query 'Users[*].UserName' --output text $PROFILE_OPT --region $REGION)
  for user in $LIST_USERS;do
    COMMAND7114=$($AWSCLI iam list-access-keys --output text $PROFILE_OPT --region $REGION --user-name $user --query 'length(AccessKeyMetadata[?Status==`Active`])')
    if [[ $COMMAND7114 -gt "1" ]];then
      textFail "$user has multiple active access keys"
    else
      textPass "$user does not have multiple active access keys"
    fi
  done
}
